### ISSUE TITLE
region code with zero tailing

### ISSUE THREAD

**Issue by toshim45** [edwinkun/database-wilayah-kemendagri#1]
Hi Edwin,

I found this records `('4308', '11.1', 'ACEH SINGKIL', '11'),` and `('36', '11.01', 'ACEH SELATAN', '11'),`

Is it correct ? and I didn't find 11.10, 12.10 can you check ?

**Comment by edwin** [comment]
Hi @toshim45 
you are right, looks like ACEH SINGKIL supposed to be 11.10 instead of 11.1
missed the last zero, perhaps because i copied it from excel :man_facepalming: 

reference : 
http://www.kemendagri.go.id/media/documents/2015/02/25/l/a/lampiran_i.pdf

**Comment by kerti** [comment]
Hi @edwin,

First, thanks for the data! It's great that we have this data publicly available in a developer-friendly format.

Second, I'm wondering if we can expect this data to be maintained regularly. As we know, the data from Kemendagri often changes and sometimes it involves new administrative areas introduced in the system (pemekaran wilayah). Do you have any plans on maintaining this data, or maybe rounding up some other devs in the community to share the workload?

**Comment by edwin** [comment]
Hi @kerti, it's actually been a while since the last time ive updated the data. Because i need to parse from Kemendagri's PDF files :man_facepalming:. But feel free if you want to update the data, just use pull request and i'll merge the data.

ps. unlike BPS, somehow kemendagri doesnt have any api yet :rofl:

**Comment by kerti** [comment]
Thanks @edwin!

Btw are you actively using this data for your own projects?

**Comment by edwin** [comment]
definitely @kerti, 
no complain whatsoever from my users until now. Or at least until Sub-Districts level :smile:

**Comment by kerti** [comment]
Well your data is pretty accurate AFAIK, just a few inconsistencies as @toshim45 mentioned. We'll probably create a pull request some time in the future. Thanks again @edwin 😄

**Comment by edwin** [comment]
the weird thing is, there are some data according to BPS that somehow different compared to Kemendagri's. Weird isnt it :rofl:
