### ISSUE TITLE
duplicate region name "inobonto"

### ISSUE THREAD

**Issue by toshim45** [edwinkun/database-wilayah-kemendagri#2]
Hi Edwin, 

sorry it's me again hehehe, but I found this issue, could u check ?

```
INSERT INTO `tbl_regions` VALUES ('68355', '71.01.13.1006', 'Inobonto', '71.01.13');
INSERT INTO `tbl_regions` VALUES ('68357', '71.01.13.2014', 'Inobonto', '71.01.13');
```

Regards,

**Comment by edwin** [comment]
hi mas @toshim45 , 
according to [this link ](http://www.kemendagri.go.id/media/filemanager/2015/08/18/7/1/71._sulut.pdf), Inobonto really have two codes. One is on "Kelurahan" level, while the other one is on "Desa". 

Trivia, there is another "Inobonto" on id 68356. Check it out :rofl:

**Comment by toshim45** [comment]
ah okey, then our kemendagri is not so creative hhaha, thanks a lot om @edwin
